import 'pet_food_model.dart';

class PetFoodService {
  static List<PetFoodModel> getAllPetFoods() {
    return [
      DogFood(
        id: 1,
        name: 'Royal Canin Adult Medium',
        brand: 'Royal Canin',
        category: 'Dry Food',
        price: 390000,
        imageUrl: 'assets/images/royalcaninmedium.png',
        description: 'Makanan anjing dewasa dengan nutrisi seimbang',
        weight: 2.0,
        stock: 25,
        ageGroup: 'adult',
        specialFeatures: ['Dental Care', 'Digestive Health'],
      ),
      CatFood(
        id: 2,
        name: 'Whiskas Adult Indoor',
        brand: 'Whiskas',
        category: 'Wet Food',
        price: 75000,
        imageUrl: 'assets/images/whiskas.png',
        description: 'Makanan kucing dewasa khusus indoor',
        weight: 0.4,
        stock: 50,
        isIndoor: true,
        lifestage: 'adult',
        healthBenefits: ['Hair Ball Control', 'Weight Management'],
      ),
      DogFood(
        id: 3,
        name: 'Pedigree Puppy',
        brand: 'Pedigree',
        category: 'Dry Food',
        price: 71000,
        imageUrl: 'assets/images/pedigree.png',
        description: 'Makanan anak anjing dengan DHA untuk perkembangan otak',
        weight: 1.5,
        stock: 30,
        ageGroup: 'puppy',
        specialFeatures: ['DHA', 'Calcium'],
      ),
      CatFood(
        id: 4,
        name: 'Pro Plan Kitten',
        brand: 'Pro Plan',
        category: 'Dry Food',
        price: 250000,
        imageUrl: 'assets/images/proplan.png',
        description: 'Makanan anak kucing dengan OptiStart',
        weight: 1.0,
        stock: 15,
        isIndoor: false,
        lifestage: 'kitten',
        healthBenefits: ['OptiStart', 'Immune Support'],
      ),
      BirdFood(
        id: 5,
        name: 'Versele Premium Bird Food',
        brand: 'Versele-Laga',
        category: 'Seeds',
        price: 60000,
        imageUrl: 'assets/images/verselebird.jpeg',
        description: 'Makanan burung premium dengan biji-bijian pilihan',
        weight: 1.0,
        stock: 20,
        birdTypes: ['Canary', 'Finch'],
        mixType: 'Seed Mix',
        benefits: ['Rich in Vitamins', 'High Energy'],
      ),
      DogFood(
        id: 6,
        name: 'Hill\'s Science Diet Senior',
        brand: 'Hill\'s',
        category: 'Dry Food',
        price: 790000,
        imageUrl: 'assets/images/hills.jpg',
        description: 'Makanan anjing senior dengan antioksidan',
        weight: 2.5,
        stock: 12,
        ageGroup: 'senior',
        specialFeatures: ['Antioxidants', 'Joint Support'],
      ),
      FishFood(
        id: 7,
        name: 'TetraMin Tropical Flakes',
        brand: 'Tetra',
        category: 'Flakes',
        price: 55000,
        imageUrl: 'assets/images/tetramin.jpg',
        description:
            'Makanan ikan tropis harian dalam bentuk serpihan untuk meningkatkan warna dan vitalitas.',
        weight: 0.1,
        stock: 40,
        foodForm: 'Flakes',
        waterType: 'Freshwater',
        isColorEnhancing: true,
      ),
      FishFood(
        id: 8,
        name: 'Hikari Goldfish Gold',
        brand: 'Hikari',
        category: 'Pellets',
        price: 55000,
        imageUrl: 'assets/images/hikari.jpg',
        description:
            'Pelet premium mengapung untuk meningkatkan pertumbuhan dan warna pada ikan koki.',
        weight: 0.2,
        stock: 22,
        foodForm: 'Pellets',
        waterType: 'Freshwater',
        isColorEnhancing: true,
      ),
      CatFood(
        id: 9,
        name: 'Royal Canin Indoor Adult',
        brand: 'Royal Canin',
        category: 'Wet Food',
        price: 310000,
        imageUrl: 'assets/images/royalcanin.png',
        description: 'Makanan kucing dewasa khusus indoor',
        weight: 0.4,
        stock: 50,
        isIndoor: true,
        lifestage: 'adult',
        healthBenefits: ['Hair Ball Control', 'Weight Management'],
      ),
      DogFood(
        id: 10,
        name: 'Cesar Classic Loaf in Sauce',
        brand: 'Cesar',
        category: 'Wet Food',
        price: 115000,
        imageUrl: 'assets/images/cesar.png',
        description:
            'Makanan anjing basah dengan potongan daging asli dalam saus lezat.',
        weight: 0.1,
        stock: 20,
        ageGroup: 'adult',
        specialFeatures: ['High Palatability', 'Real Meat'],
      ),
      DogFood(
        id: 11,
        name: 'Acana Wild Prairie (Grain-Free)',
        brand: 'Acana',
        category: 'Dry Food',
        price: 1899000,
        imageUrl: 'assets/images/acana.png',
        description:
            'Formula bebas biji-bijian dengan ayam, kalkun, dan ikan segar.',
        weight: 2.0,
        stock: 10,
        ageGroup: 'all stages',
        specialFeatures: ['Grain-Free', 'High Protein'],
      ),
      DogFood(
        id: 12,
        name: 'Eukanuba Large Breed Adult',
        brand: 'Eukanuba',
        category: 'Dry Food',
        price: 1900000,
        imageUrl: 'assets/images/eukanuba.png',
        description:
            'Diformulasikan khusus untuk anjing ras besar dewasa untuk mendukung sendi yang sehat.',
        weight: 3.0,
        stock: 22,
        ageGroup: 'adult',
        specialFeatures: ['Joint Support', 'For Large Breeds'],
      ),
      CatFood(
        id: 13,
        name: 'Me-O Cat Food Senior',
        brand: 'Me-O',
        category: 'Dry Food',
        price: 35000,
        imageUrl: 'assets/images/meo_senior.png',
        description:
            'Makanan untuk kucing senior (7+ tahun) untuk menjaga kesehatan ginjal dan sendi.',
        weight: 1.1,
        stock: 35,
        isIndoor: true,
        lifestage: 'senior',
        healthBenefits: ['Kidney Support', 'Joint Care'],
      ),
      CatFood(
        id: 14,
        name: 'Royal Canin Sensitive Digestion',
        brand: 'Royal Canin',
        category: 'Dry Food',
        price: 420000,
        imageUrl: 'assets/images/rc_sensitive.png',
        description: 'Untuk kucing dewasa dengan sistem pencernaan sensitif.',
        weight: 2.0,
        stock: 19,
        isIndoor: true,
        lifestage: 'adult',
        healthBenefits: ['Digestive Health', 'High Digestibility'],
      ),
      BirdFood(
        id: 15,
        name: 'Prestige Premium Lovebird Food',
        brand: 'Versele-Laga',
        category: 'Seeds',
        price: 85000,
        imageUrl: 'assets/images/prestige_lovebird.png',
        description:
            'Campuran biji-bijian premium yang diperkaya khusus untuk burung lovebird.',
        weight: 0.8,
        stock: 28,
        birdTypes: ['Lovebird'],
        mixType: 'Seed Mix',
        benefits: ['Enriched with Vitamins', 'Optimal Digestion'],
      ),
      BirdFood(
        id: 16,
        name: 'Tops Organic Parrot Pellets',
        brand: 'Tops',
        category: 'Pellets',
        price: 210000,
        imageUrl: 'assets/images/tops_pellets.png',
        description:
            'Pelet burung organik, alami, dan tanpa bahan pengawet buatan.',
        weight: 0.45,
        stock: 15,
        birdTypes: ['Parrot', 'Macaw', 'Cockatoo'],
        mixType: 'Pellets',
        benefits: ['Organic', 'No Fillers'],
      ),
      BirdFood(
        id: 17,
        name: 'Kaytee Lori Nectar',
        brand: 'Kaytee',
        category: 'Nectar',
        price: 150000,
        imageUrl: 'assets/images/kaytee_nectar.png',
        description:
            'Makanan berupa nektar yang mudah dicerna untuk burung Lori dan sejenisnya.',
        weight: 0.5,
        stock: 20,
        birdTypes: ['Lory', 'Lorikeet'],
        mixType: 'Nectar',
        benefits: ['Easy to Digest', 'Complete Nutrition'],
      ),
      FishFood(
        id: 18,
        name: 'Hikari Sinking Wafers',
        brand: 'Hikari',
        category: 'Wafers',
        price: 90000,
        imageUrl: 'assets/images/hikari_wafers.png',
        description:
            'Wafer tenggelam untuk ikan pemakan dasar seperti Corydoras dan Plecos.',
        weight: 0.11,
        stock: 33,
        foodForm: 'Wafers',
        waterType: 'Freshwater',
        isColorEnhancing: false,
      ),
      FishFood(
        id: 19,
        name: 'Ocean Nutrition Betta Pro',
        brand: 'Ocean Nutrition',
        category: 'Pellets',
        price: 45000,
        imageUrl: 'assets/images/atison.png',
        description:
            'Pelet kecil yang dirancang khusus untuk meningkatkan warna dan vitalitas ikan cupang.',
        weight: 0.02,
        stock: 50,
        foodForm: 'Pellets',
        waterType: 'Freshwater',
        isColorEnhancing: true,
      ),
      FishFood(
        id: 20,
        name: 'New Life Spectrum Marine',
        brand: 'New Life Spectrum',
        category: 'Pellets',
        price: 180000,
        imageUrl: 'assets/images/spectrum.png',
        description:
            'Pelet untuk semua jenis ikan air asin, diperkaya dengan bawang putih untuk kekebalan tubuh.',
        weight: 0.12,
        stock: 25,
        foodForm: 'Pellets',
        waterType: 'Saltwater',
        isColorEnhancing: true,
      ),
    ];
  }

  static List<PetFoodModel> getPetFoodByAnimalType(String animalType) {
    return getAllPetFoods()
        .where((food) => food.animalType == animalType)
        .toList();
  }

  static List<PetFoodModel> getPetFoodByBrand(String brand) {
    return getAllPetFoods().where((food) => food.brand == brand).toList();
  }

  static List<PetFoodModel> searchPetFood(String query) {
    return getAllPetFoods()
        .where((food) => food.name.toLowerCase().contains(query.toLowerCase()))
        .toList();
  }

  static List<PetFoodModel> getAvailablePetFood() {
    return getAllPetFoods().where((food) => food.isAvailable).toList();
  }
}