// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ4nR8DT3mDhYt0xM-r5kTZIKIVNHnbo8',
    appId: '1:390486147963:web:e384bc97925b35b02433de',
    messagingSenderId: '390486147963',
    projectId: 'pawmartdb',
    authDomain: 'pawmartdb.firebaseapp.com',
    storageBucket: 'pawmartdb.firebasestorage.app',
    measurementId: 'G-M6H0K8Q58F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwAuCxbs-eBjwPrTDnGNzJj1BtPn2gBoQ',
    appId: '1:390486147963:android:2031e21bdca34e582433de',
    messagingSenderId: '390486147963',
    projectId: 'pawmartdb',
    storageBucket: 'pawmartdb.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ4nR8DT3mDhYt0xM-r5kTZIKIVNHnbo8',
    appId: '1:390486147963:web:4a4ec842516085c52433de',
    messagingSenderId: '390486147963',
    projectId: 'pawmartdb',
    authDomain: 'pawmartdb.firebaseapp.com',
    storageBucket: 'pawmartdb.firebasestorage.app',
    measurementId: 'G-FYJG59BZMK',
  );
}
